apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-datascientest
  labels:
    app: {{ .Release.Name }}-datascientest
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-datascientest
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-datascientest
    spec:
      containers:
        - name:     {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP